### ISSUE TITLE
Add a mechanism to indicate if COSP is turned off?

### ISSUE THREAD

**Issue by susburrows** [E3SM-Project/processflow#109]
Sometimes we run the model without COSP, in which case some packages (e.g. AMWG) produce a bunch of error messages because they can't find diagnostics they are expecting.  It might be a nice addition to have an option to indicate that COSP is turned off. (but this is not urgent/critical)

**Comment by sterlingbaldwin** [comment]
It would be approximately the same amount of effort to do either of the following two options:

1) Add an option like, "run_cosp = False", or
2) Add an option like, "amwg_sets = ['set_1', 'set_2, 'set_3']' allowing of course "amwg_sets = 'all' "

The first is nice since the user just has a single self-explanatory flag to turn on/off, but its not very configurable. If in the future someone else wants set_13 (COSP cloud simulator plots) turned on but doesnt care about something like set_15 (Annual Cycle Plots for Select stations) they dont have the option.

The second gives the user additional control over exactly what is run, but with the danger of creating too many options and breeding confusion/choice overload. I'm inclined to go with option two, since it would mean I wouldn't have to come back later and add additional configuration when the next person wants to turn on/off the next set, but Im happy either way.

**Comment by rljacob** [comment]
I like the second option too.

**Comment by susburrows** [comment]
Thanks @sterlingbaldwin !  I also like the second option, but would prefer if a comment could also be included directly in the script that mentions what each of the "sets" is.  The naming convention is extremely uninformative.

**Comment by sterlingbaldwin** [comment]
Done, I added the ```sets = 'all'``` or ```sets = 3, 4, 4a, 5, 13``` options. The second option is just a comma seperated list of what sets you want and works with all the sets, ones listed are just an example. I agree that the term "sets" is sub-optimal, but since its how the amwg script describes the plot sets its what I went with.
